/**
 * AArch64 code generation through a linear intermediate representation on
 * virtual registers with a global register allocator.
 *
 * The elem trees of each block are selected into machine instructions on
 * virtual registers, the live ranges of those are allocated to the physical
 * registers by spill cost, and the result is emitted as the blocks' `Bcode`,
 * which the rest of `codgenx()` lays out and writes as it does the code of
 * the tree code generator. A function using anything not handled here is
 * generated by the tree code generator.
 *
 * Copyright:   Copyright (C) 2026 by The D Language Foundation, All Rights Reserved
 * License:     $(LINK2 https://www.boost.org/LICENSE_1_0.txt, Boost License 1.0)
 * Source:      $(LINK2 https://github.com/dlang/dmd/blob/master/compiler/src/dmd/backend/arm/lir.d, backend/arm/lir.d)
 */

module dmd.backend.arm.lir;

import core.stdc.stdio;
import core.stdc.stdlib;
import core.stdc.string;

import dmd.backend.barray;
import dmd.backend.blockopt : bo;
import dmd.backend.cc;
import dmd.backend.cdef;
import dmd.backend.code;
import dmd.backend.codebuilder;
import dmd.backend.el;
import dmd.backend.global : REGSIZE, mask;
import dmd.backend.oper;
import dmd.backend.symbol;
import dmd.backend.ty;
import dmd.backend.type;
import dmd.backend.x86.code_x86;
import dmd.backend.arm.cod1 : loadFromEA, storeToEA;
import dmd.backend.arm.cod3 : COND, genBranch, movregconstant;
import dmd.backend.arm.instr;

nothrow:
@safe:

/* Register operands: 0 is none, 1 .. 64 are the physical registers 0 .. 63
 * (x0 .. x31, then v0 .. v31), and the rest are virtual registers
 */
alias Reg = uint;
enum Reg noReg = 0;
enum Reg firstVreg = 65;

Reg phys(uint r) { return r + 1; }
bool isPhys(Reg r) { return r && r < firstVreg; }
uint physOf(Reg r) { assert(isPhys(r)); return r - 1; }

/// Register classes
enum RC : ubyte { gp, fp }

/// Operations of the intermediate representation
enum LOp : ubyte
{
    nop,
    label,          // target: label number
    copy,           // d = a
    movi,           // d = imm
    fmovi,          // d = the float or double whose bits are imm
    add, sub, mul, sdiv, udiv, and_, orr, eor, lslv, lsrv, asrv,   // d = a op b
    addi, subi, lsli, lsri, asri, andi, orri, eori,                // d = a op imm
    msub,           // d = c - a * b
    neg,            // d = -a
    mvn,            // d = ~a
    sext,           // d = a sign extended from imm bits
    zext,           // d = a zero extended from imm bits
    cmp,            // flags = a - b
    cmpi,           // flags = a - imm
    cset,           // d = cond
    csel,           // d = cond ? a : b
    fadd, fsub, fmul, fdiv,                                        // d = a op b
    fneg, fabs, fsqrt,                                             // d = op a
    fcmp,           // flags = a <=> b
    fcmpz,          // flags = a <=> 0
    fcsel,          // d = cond ? a : b
    scvtf, ucvtf,   // d = float a, sz is the float size, imm the int size
    fcvtzs, fcvtzu, // d = int a, sz is the int size, imm the float size
    fcvt,           // d = a converted to size sz from size imm
    ld,             // d = memory at [a + imm] or sym + imm, sz bytes, flags F.signed
    st,             // memory at [b + imm] or sym + imm = a, sz bytes
    lea,            // d = &sym + imm
    br,             // jump to target
    bcond,          // jump to target if cond
    brk,            // trap
}

/// Flags of an instruction
enum F : ubyte
{
    signed  = 1,    // ld sign extends
    toLabel = 2,    // target is a label rather than a block
    condDef = 4,    // a definition that is made on only some paths through its block
}

/// An instruction of the intermediate representation
struct LIns
{
    LOp op;
    ubyte sz;           // operand size in bytes
    ubyte cond;         // COND
    ubyte flags;        // F
    Reg d, a, b, c;
    long imm;
    Symbol* sym;
    uint target;        // block or label number
}

/// A live range [from, to) in instruction positions
struct Range
{
    uint from, to;
}

/// What is known about a virtual register
struct VInfo
{
    RC rc;
    ubyte sz;                   // largest size it holds
    bool global;                // live in more than one block
    bool spilled;
    uint preg = uint.max;       // physical register allocated
    uint firstBlock = uint.max; // block it was first seen in
    float cost = 0;             // spill cost: weighted number of uses and definitions
    Reg hint;                   // register it is copied to or from
    Symbol* slot;               // stack slot when spilled
    Symbol* sym;                // the variable it holds, if any
    Barray!Range ranges;        // sorted, disjoint
    uint globalId = uint.max;   // index in the live variable bit sets
}

private __gshared
{
    Barray!LIns ins;
    Barray!VInfo vinfo;         // indexed by Reg - firstVreg
    Barray!(block*) blocks;     // in layout order
    Barray!uint blockStart;     // first instruction of each block, then the end
    Barray!Reg symReg;          // by globsym index: the register of the variable, or noReg
    Barray!uint savedDfoidx;
    uint nlabels;
    Barray!uint labelPos;       // instruction index of each label
    CGstate* cgp;
    bool failed;                // the function uses something not handled
    Barray!(elem*) cseElems;    // CSEs evaluated, with their registers in cseRegs
    Barray!Reg cseRegs;
    uint curBlock;
    uint condDepth;             // number of conditionally evaluated regions being selected
    bool usesFrame;             // the code refers to locals or parameters in memory
}

/// Whether the new code generator is enabled, from DMD_NEWCG, and for which
/// functions, from DMD_NEWCG_NAME (a substring of the mangled name)
@trusted
private bool enabledFor(const(char)* name)
{
    __gshared int enabled = -1;
    __gshared const(char)* filter;
    if (enabled < 0)
    {
        auto p = getenv("DMD_NEWCG");
        enabled = p && *p != '0';
        filter = getenv("DMD_NEWCG_NAME");
    }
    if (!enabled)
        return false;
    if (filter && !strstr(name, filter))
        return false;
    // DMD_NEWCG_MAX limits it to that many functions, for bisecting
    __gshared long limit = -2;
    __gshared long count;
    if (limit == -2)
    {
        auto p = getenv("DMD_NEWCG_MAX");
        limit = p ? atoll(p) : -1;
    }
    return limit < 0 || count++ < limit;
}

/***************************************
 * Generate the code of the function's blocks into their Bcode.
 * Returns:
 *      false if the function uses something not handled, with nothing changed
 */
@trusted
bool lirCodegen(ref CGstate cg)
{
    if (!enabledFor(funcsym_p.Sident.ptr))
        return false;
    if (!supported(cg))
        return false;

    cgp = &cg;
    failed = false;
    ins.setLength(0);
    foreach (ref v; vinfo[])
        v.ranges.dtor();
    vinfo.setLength(0);
    blocks.setLength(0);
    blockStart.setLength(0);
    nlabels = 0;
    labelPos.setLength(0);
    cseElems.setLength(0);
    cseRegs.setLength(0);
    usesFrame = false;
    condDepth = 0;

    for (block* b = bo.startblock; b; b = b.Bnext)
        blocks.push(b);
    savedDfoidx.setLength(blocks.length);
    foreach (i, b; blocks[])
    {
        savedDfoidx[i] = b.Bdfoidx;
        b.Bdfoidx = cast(uint)i;
    }
    scope (exit)
        foreach (i, b; blocks[])
            b.Bdfoidx = savedDfoidx[i];

    assignVariables();
    select();
    if (failed)
    {
        undoVariables();
        return false;
    }
    computeLiveness();
    allocate();
    if (getenv("DMD_NEWCG_DUMP"))
        dump();
    rewriteSpills();
    emit(cg);
    finishVariables();
    if (getenv("DMD_NEWCG_LOG"))
        fprintf(stderr, "newcg: %s\n", funcsym_p.Sident.ptr);
    return true;
}

/******************************* Support check ******************************/

/* Whether every block and elem of the function is handled
 */
@trusted
private bool supported(ref CGstate cg)
{
    if (funcsym_p.ty() & mTYnaked)
        return false;
    if (variadic(funcsym_p.Stype))
        return false;
    if (cg.Alloca.size)
        return false;
    const tyr = tybasic(funcsym_p.Stype.Tnext.Tty);
    if (tyr != TYvoid && !scalarType(tyr))
        return false;

    foreach (s; globsym[])
    {
        switch (s.Sclass)
        {
            case SC.auto_:
            case SC.register:
            case SC.parameter:
                break;
            case SC.fastpar:
                if (s.Spreg2 != NOREG && !(s.Sflags & SFLdead))
                    return false;
                break;
            default:
                return false;
        }
    }

    for (block* b = bo.startblock; b; b = b.Bnext)
    {
        switch (b.bc)
        {
            case BC.goto_:
            case BC.iftrue:
            case BC.ret:
                break;
            case BC.retexp:
                if (!b.Belem)
                    return false;
                break;
            default:
                return false;
        }
        if (b.Btry)
            return false;
        if (b.Belem && !supportedElem(b.Belem))
            return false;
    }
    return true;
}

/* Whether ty is an integer, pointer, float or double held in one register
 */
private bool scalarType(tym_t ty)
{
    ty = tybasic(ty);
    if (tyfloating(ty))
        return (ty == TYfloat || ty == TYdouble || ty == TYidouble || ty == TYifloat ||
                ty == TYdouble_alias);
    if (tyintegral(ty) || typtr(ty) || ty == TYnullptr || ty == TYbool)
    {
        const sz = tysize(ty);
        return sz == 1 || sz == 2 || sz == 4 || sz == 8;
    }
    return false;
}

@trusted
private bool supportedElem(const(elem)* e)
{
    while (1)
    {
        const op = e.Eoper;
        if (!(op == OPcolon) && !(op == OPcomma) && !(op == OPeq) &&
            !scalarType(e.Ety) && tybasic(e.Ety) != TYvoid)
            return false;
        switch (op)
        {
            case OPconst:
            case OPvar:
                if (op == OPvar && !varSupported(e.Vsym))
                    return false;
                return true;

            case OPrelconst:
                return varSupported(e.Vsym);

            case OPind:
            case OPneg:
            case OPcom:
            case OPnot:
            case OPbool:
            case OPs32_64: case OPu32_64: case OP64_32:
            case OPu8_16: case OPs8_16: case OP16_8:
            case OPu16_32: case OPs16_32: case OP32_16:
            case OPsqrt:
            case OPabs:
            case OPd_f: case OPf_d:
            case OPs32_d: case OPu32_d: case OPs64_d: case OPu64_d:
            case OPd_s32: case OPd_u32: case OPd_s64: case OPd_u64:
            case OPd_s16: case OPd_u16:
            case OPhalt:
                if (OTunary(op))
                {
                    e = e.E1;
                    continue;
                }
                return true;

            case OPadd: case OPmin: case OPmul: case OPdiv: case OPmod:
            case OPand: case OPor: case OPxor:
            case OPshl: case OPshr: case OPashr:
            case OPeq:
            case OPcomma:
            case OPandand: case OPoror:
            case OPcond: case OPcolon:
            case OPlt: case OPle: case OPgt: case OPge: case OPeqeq: case OPne:
            case OPaddass: case OPminass: case OPmulass: case OPdivass: case OPmodass:
            case OPandass: case OPorass: case OPxorass:
            case OPshlass: case OPshrass: case OPashrass:
            case OPpostinc: case OPpostdec:
                if (op == OPeq && !scalarType(e.Ety))
                    return false;
                if (!supportedElem(e.E1))
                    return false;
                e = e.E2;
                continue;

            default:
                return false;
        }
    }
}

/* Whether references to s are handled
 */
@trusted
private bool varSupported(const Symbol* s)
{
    switch (s.Sclass)
    {
        case SC.auto_:
        case SC.register:
        case SC.parameter:
        case SC.fastpar:
            return true;
        default:
            return false;
    }
}

/******************************* Variables ******************************/

/* Give the register candidates virtual registers
 */
@trusted
private void assignVariables()
{
    symReg.setLength(globsym.length);
    symReg[][] = noReg;

    // a candidate is only ever accessed whole
    Barray!bool partial;
    partial.setLength(globsym.length);
    partial[][] = false;
    void mark(const(elem)* e)
    {
        while (1)
        {
            if (e.Eoper == OPvar || e.Eoper == OPrelconst)
            {
                const s = e.Vsym;
                const k = s.Ssymnum;
                if (k < globsym.length && globsym[k] is s)
                {
                    if (e.Eoper == OPrelconst || e.Voffset != 0 ||
                        tysize(e.Ety) != tysize(s.Stype.Tty))
                        partial[k] = true;
                }
                return;
            }
            if (OTbinary(e.Eoper))
            {
                mark(e.E2);
                e = e.E1;
            }
            else if (OTunary(e.Eoper))
                e = e.E1;
            else
                return;
        }
    }
    for (block* b = bo.startblock; b; b = b.Bnext)
        if (b.Belem)
            mark(b.Belem);

    foreach (k, s; globsym[])
    {
        if (partial[k])
            continue;
        if (!(s.Sflags & GTregcand) || s.ty() & (mTYvolatile | mTYshared))
            continue;
        if (!scalarType(s.Stype.Tty))
            continue;
        if (s.Sflags & SFLdead)
            continue;
        const sz = tysize(s.Stype.Tty);
        Reg r = newVreg(tyfloating(s.Stype.Tty) ? RC.fp : RC.gp, sz);
        vinfo[r - firstVreg].sym = s;
        symReg[k] = r;
    }
    partial.dtor();
}

/* The register variable r holds, or null
 */
@trusted
private Reg varReg(const Symbol* s)
{
    const k = s.Ssymnum;
    if (k < symReg.length && globsym[k] is s)
        return symReg[k];
    return noReg;
}

private void undoVariables()
{
}

/* Make the variables given registers registers to the rest of the code
 * generator, so they get no stack space and their parameters stay where
 * they are passed
 */
@trusted
private void finishVariables()
{
    foreach (k, s; globsym[])
    {
        const r = symReg[k];
        if (!r)
            continue;
        const v = &vinfo[r - firstVreg];
        if (s.Sclass == SC.parameter)
            continue;           // its stack slot is the caller's
        s.Sfl = FL.reg;
        const preg = s.Sclass == SC.fastpar ? s.Spreg : (v.spilled ? 0 : v.preg);
        s.Sreglsw = cast(reg_t)preg;
        s.Sregmsw = NOREG;
        s.Sregm = mask(preg);
    }
}

/******************************* Selection ******************************/

@trusted
private Reg newVreg(RC rc, uint sz)
{
    VInfo vi;
    vi.rc = rc;
    vi.sz = cast(ubyte)sz;
    vinfo.push(vi);
    return cast(Reg)(firstVreg + vinfo.length - 1);
}

@trusted
private VInfo* vi(Reg r) { return &vinfo[r - firstVreg]; }

@trusted
private RC rcOf(Reg r)
{
    if (isPhys(r))
        return physOf(r) >= 32 ? RC.fp : RC.gp;
    return vinfo[r - firstVreg].rc;
}

@trusted
private LIns* emitIns(LOp op, uint sz, Reg d = noReg, Reg a = noReg, Reg b = noReg, long imm = 0)
{
    LIns i;
    i.op = op;
    i.sz = cast(ubyte)sz;
    i.d = d;
    i.a = a;
    i.b = b;
    i.imm = imm;
    ins.push(i);
    return &ins[ins.length - 1];
}

@trusted
private uint newLabel()
{
    labelPos.push(uint.max);
    return nlabels++;
}

@trusted
private void placeLabel(uint l)
{
    auto i = emitIns(LOp.label, 0);
    i.target = l;
}

@trusted
private void jumpTo(uint l, COND cond = COND.al)
{
    auto i = emitIns(cond == COND.al ? LOp.br : LOp.bcond, 0);
    i.cond = cond;
    i.target = l;
    i.flags = F.toLabel;
}

@trusted
private void jumpToBlock(block* b, COND cond = COND.al)
{
    auto i = emitIns(cond == COND.al ? LOp.br : LOp.bcond, 0);
    i.cond = cond;
    i.target = b.Bdfoidx;
}

/* Select the instructions of all the blocks
 */
@trusted
private void select()
{
    blockStart.push(0);
    // copy the parameters out of the registers they are passed in
    foreach (k, s; globsym[])
    {
        const r = symReg[k];
        if (!r)
            continue;
        if (s.Sclass == SC.fastpar)
        {
            emitIns(LOp.copy, rcOf(r) == RC.fp ? tysize(s.Stype.Tty) : 8, r, phys(s.Spreg));
            vi(r).hint = phys(s.Spreg);
        }
        else if (s.Sclass == SC.parameter)
        {
            auto i = emitIns(LOp.ld, tysize(s.Stype.Tty), r);
            i.sym = s;
            i.flags = tyuns(s.Stype.Tty) ? 0 : F.signed;
            usesFrame = true;
        }
    }

    foreach (bi, b; blocks[])
    {
        curBlock = cast(uint)bi;
        if (bi)
            blockStart.push(cast(uint)ins.length);
        block* next = bi + 1 < blocks.length ? blocks[bi + 1] : null;
        switch (b.bc)
        {
            case BC.goto_:
                if (b.Belem)
                    genEffect(b.Belem);
                if (b.Bsucc[0] != next)
                    jumpToBlock(b.Bsucc[0]);
                break;

            case BC.iftrue:
            {
                block* bt = b.Bsucc[0];
                block* bf = b.Bsucc[1];
                if (bt == next)
                    genCondBlock(b.Belem, false, bf);
                else
                {
                    genCondBlock(b.Belem, true, bt);
                    if (bf != next)
                        jumpToBlock(bf);
                }
                break;
            }

            case BC.ret:
                if (b.Belem)
                    genEffect(b.Belem);
                break;

            case BC.retexp:
            {
                elem* e = b.Belem;
                const ty = tybasic(funcsym_p.Stype.Tnext.Tty);
                Reg r = gen(e);
                if (tyfloating(ty))
                    emitIns(LOp.copy, tysize(ty), phys(32), r);
                else
                {
                    const sz = tysize(ty);
                    if (sz < 4)
                        // the caller expects a value narrower than 32 bits extended to 32
                        r = extend(r, ty, 4);
                    emitIns(LOp.copy, 8, phys(0), r);
                }
                break;
            }

            default:
                assert(0);
        }
        if (failed)
            return;
    }
    blockStart.push(cast(uint)ins.length);
}

/* r extended from the size of ty to toSize bytes
 */
@trusted
private Reg extend(Reg r, tym_t ty, uint toSize)
{
    const sz = tysize(ty);
    if (sz >= toSize)
        return r;
    Reg d = newVreg(RC.gp, toSize);
    emitIns(tyuns(ty) || tybasic(ty) == TYbool ? LOp.zext : LOp.sext, toSize, d, r, noReg, sz * 8);
    return d;
}

/* Evaluate e for its side effects
 */
@trusted
private void genEffect(elem* e)
{
    switch (e.Eoper)
    {
        case OPcomma:
            genEffect(e.E1);
            genEffect(e.E2);
            return;

        case OPconst:
        case OPrelconst:
            return;

        case OPvar:
            if (!e.Ecount && !(e.Vsym.ty() & mTYvolatile))
                return;
            break;

        case OPcond:
        {
            const lfalse = newLabel();
            const lend = newLabel();
            genCond(e.E1, false, lfalse);
            auto m = enterCond();
            genEffect(e.E2.E1);
            leaveCond(m);
            jumpTo(lend);
            placeLabel(lfalse);
            m = enterCond();
            genEffect(e.E2.E2);
            leaveCond(m);
            placeLabel(lend);
            return;
        }

        case OPandand:
        case OPoror:
        {
            const lend = newLabel();
            genCond(e.E1, e.Eoper == OPoror, lend);
            const m = enterCond();
            genEffect(e.E2);
            leaveCond(m);
            placeLabel(lend);
            return;
        }

        default:
            break;
    }
    gen(e);
}

/* Jump to block t if e is true (or false if !jumpIfTrue)
 */
@trusted
private void genCondBlock(elem* e, bool jumpIfTrue, block* t)
{
    genCond(e, jumpIfTrue, uint.max, t);
}

/* Jump to label l (or block t if not null) if e is true (or false if !jumpIfTrue)
 */
@trusted
private void genCond(elem* e, bool jumpIfTrue, uint l, block* t = null)
{
    void jump(COND cond)
    {
        if (t)
            jumpToBlock(t, cond);
        else
            jumpTo(l, cond);
    }

    if (e.Ecount)
    {
        valueCond(e, jumpIfTrue, &jump);
        return;
    }

    switch (e.Eoper)
    {
        case OPcomma:
            genEffect(e.E1);
            genCond(e.E2, jumpIfTrue, l, t);
            return;

        case OPnot:
            genCond(e.E1, !jumpIfTrue, l, t);
            return;

        case OPandand:
        case OPoror:
        {
            const isAnd = e.Eoper == OPandand;
            if (jumpIfTrue == isAnd)
            {
                // a && b true: both true; a || b false: both false
                const lskip = newLabel();
                genCond(e.E1, !jumpIfTrue, lskip);
                const m = enterCond();
                genCond(e.E2, jumpIfTrue, l, t);
                leaveCond(m);
                placeLabel(lskip);
            }
            else
            {
                genCond(e.E1, jumpIfTrue, l, t);
                const m = enterCond();
                genCond(e.E2, jumpIfTrue, l, t);
                leaveCond(m);
            }
            return;
        }

        case OPlt: case OPle: case OPgt: case OPge: case OPeqeq: case OPne:
        {
            COND c = compare(e);
            jump(jumpIfTrue ? c : cast(COND)(c ^ 1));
            return;
        }

        default:
            valueCond(e, jumpIfTrue, &jump);
            return;
    }
}

/* Jump if the value of e is nonzero (or zero if !jumpIfTrue)
 */
@trusted
private void valueCond(elem* e, bool jumpIfTrue, scope void delegate(COND) nothrow jump)
{
    Reg r = gen(e);
    if (tyfloating(e.Ety))
        emitIns(LOp.fcmpz, tysize(e.Ety), noReg, r);
    else
    {
        const sz = tysize(e.Ety);
        if (sz < 4)
            r = extend(r, e.Ety, 4);
        emitIns(LOp.cmpi, sz <= 4 ? 4 : 8, noReg, r, noReg, 0);
    }
    jump(jumpIfTrue ? COND.ne : COND.eq);
}

/* Set the flags for the relational e, returning the condition for it being true
 */
@trusted
private COND compare(elem* e)
{
    elem* e1 = e.E1;
    elem* e2 = e.E2;
    const ty = e1.Ety;
    int i;
    if (tyfloating(ty))
        i = 2;
    else if (tyuns(ty) || tyuns(e2.Ety))
        i = 1;
    else
        i = 0;

    with (COND)
    {
        immutable COND[6][3] conds =
        [   /* <=   >   <   >=  ==  != */
            [ le, gt, lt, ge, eq, ne ],     // signed
            [ ls, hi, cc, cs, eq, ne ],     // unsigned
            [ ls, gt, mi, ge, eq, ne ],     // floating
        ];
        const c = conds[i][e.Eoper - OPle];

        if (i == 2)
        {
            const sz = tysize(ty);
            Reg a, b;
            if (ERTOL(e)) { b = gen(e2); a = gen(e1); }
            else { a = gen(e1); b = genKeep(e2, a); }
            emitIns(LOp.fcmp, sz, noReg, a, b);
            return c;
        }

        const sz = tysize(ty);
        Reg a = gen(e1);
        if (sz < 4)
            a = extend(a, ty, 4);
        if (e2.Eoper == OPconst && !e2.Ecount)
        {
            const long v = el_tolong(e2);
            if (v >= 0 && v < 4096)
            {
                emitIns(LOp.cmpi, sz <= 4 ? 4 : 8, noReg, a, noReg, v);
                return c;
            }
        }
        Reg b = genKeep(e2, a);
        if (sz < 4)
            b = extend(b, e2.Ety, 4);
        emitIns(LOp.cmp, sz <= 4 ? 4 : 8, noReg, a, b);
        return c;
    }
}

/* Evaluate e after a value in r whose register variable e may assign,
 * copying r if so
 */
@trusted
private Reg genKeep(elem* e, ref Reg r)
{
    if (vi(r).sym && el_sideeffect(e))
    {
        Reg t = newVreg(vi(r).rc, vi(r).sz);
        emitIns(LOp.copy, vi(r).sz, t, r);
        r = t;
    }
    return gen(e);
}

/* Start and end the selection of code that runs on only some paths through
 * its block. The CSEs evaluated by it are forgotten when it is left, and the
 * variables it assigns are not dead before it
 */
@trusted
private size_t enterCond()
{
    ++condDepth;
    return cseElems.length;
}

@trusted
private void leaveCond(size_t mark)
{
    --condDepth;
    cseForget(mark);
}

/* Copy a into d, which outlives the code being selected
 */
@trusted
private void copyOut(Reg d, Reg a, uint sz)
{
    auto i = emitIns(LOp.copy, sz, d, a);
    if (condDepth)
        i.flags |= F.condDef;
}

/* Mark where d, assigned only conditionally below, starts being live
 */
@trusted
private void defineHere(Reg d)
{
    emitIns(LOp.nop, 0, d);
}

/* The CSEs evaluated so far, to forget those evaluated by code that may not
 * run once it is left
 */
@trusted
private size_t cseMark() { return cseElems.length; }

@trusted
private void cseForget(size_t mark)
{
    cseElems.setLength(mark);
    cseRegs.setLength(mark);
}

@trusted
private Reg cseLookup(elem* e)
{
    foreach (i, x; cseElems[])
        if (x is e)
            return cseRegs[i];
    return noReg;
}

/* Evaluate e into a register
 */
@trusted
private Reg gen(elem* e)
{
    if (e.Ecount)
    {
        if (Reg r = cseLookup(e))
            return r;
    }
    Reg r = genx(e);
    if (e.Ecount && r)
    {
        // a CSE of a register variable is a copy, as the variable may change
        if (vi(r).sym)
        {
            Reg t = newVreg(vi(r).rc, vi(r).sz);
            emitIns(LOp.copy, vi(r).sz, t, r);
            r = t;
        }
        cseElems.push(e);
        cseRegs.push(r);
    }
    return r;
}

/* The memory an lvalue refers to: a register base and offset, or a variable
 */
struct Mem
{
    Reg base;
    long offset;
    Symbol* sym;
}

@trusted
private Mem memOf(elem* e)
{
    Mem m;
    if (e.Eoper == OPvar)
    {
        m.sym = e.Vsym;
        m.offset = e.Voffset;
        usesFrame = true;
        return m;
    }
    assert(e.Eoper == OPind);
    elem* a = e.E1;
    if (a.Eoper == OPadd && !a.Ecount && a.E2.Eoper == OPconst && tysize(a.Ety) == 8)
    {
        const long c = el_tolong(a.E2);
        if (c > -256 && c < 0x8000)
        {
            m.base = gen(a.E1);
            m.offset = c;
            return m;
        }
    }
    m.base = gen(a);
    return m;
}

@trusted
private void load(Reg d, Mem m, tym_t ty)
{
    auto i = emitIns(LOp.ld, tysize(ty), d, m.base, noReg, m.offset);
    i.sym = m.sym;
    if (!tyuns(ty) && !tyfloating(ty) && tybasic(ty) != TYbool)
        i.flags = F.signed;
}

@trusted
private void store(Reg v, Mem m, tym_t ty)
{
    auto i = emitIns(LOp.st, tysize(ty), noReg, v, m.base, m.offset);
    i.sym = m.sym;
}

@trusted
private Reg genx(elem* e)
{
    const op = e.Eoper;
    const ty = tybasic(e.Ety);
    const sz = tysize(ty);
    const RC rc = tyfloating(ty) ? RC.fp : RC.gp;

    switch (op)
    {
        case OPconst:
        {
            Reg d = newVreg(rc, sz);
            if (rc == RC.fp)
            {
                long bits;
                if (sz == 4)
                {
                    float f = e.Vfloat;
                    bits = *cast(uint*)&f;
                }
                else
                {
                    double f = e.Vdouble;
                    bits = *cast(long*)&f;
                }
                emitIns(LOp.fmovi, sz, d, noReg, noReg, bits);
            }
            else
                emitIns(LOp.movi, sz <= 4 ? 4 : 8, d, noReg, noReg, el_tolong(e));
            return d;
        }

        case OPvar:
        {
            if (Reg r = varReg(e.Vsym))
                return r;
            Reg d = newVreg(rc, sz);
            load(d, memOf(e), ty);
            return d;
        }

        case OPrelconst:
        {
            Reg d = newVreg(RC.gp, 8);
            auto i = emitIns(LOp.lea, 8, d, noReg, noReg, e.Voffset);
            i.sym = e.Vsym;
            usesFrame = true;
            return d;
        }

        case OPind:
        {
            Reg d = newVreg(rc, sz);
            load(d, memOf(e), ty);
            return d;
        }

        case OPcomma:
            genEffect(e.E1);
            return gen(e.E2);

        case OPeq:
            return genAssign(e);

        case OPadd: case OPmin: case OPmul: case OPdiv: case OPmod:
        case OPand: case OPor: case OPxor:
        case OPshl: case OPshr: case OPashr:
            return genBinary(e);

        case OPaddass: case OPminass: case OPmulass: case OPdivass: case OPmodass:
        case OPandass: case OPorass: case OPxorass:
        case OPshlass: case OPshrass: case OPashrass:
        case OPpostinc: case OPpostdec:
            return genOpAssign(e);

        case OPneg:
        {
            Reg a = gen(e.E1);
            Reg d = newVreg(rc, sz);
            emitIns(rc == RC.fp ? LOp.fneg : LOp.neg, rc == RC.fp ? sz : (sz <= 4 ? 4 : 8), d, a);
            return d;
        }

        case OPabs:
        case OPsqrt:
        {
            if (rc != RC.fp)
            {
                failed = true;
                return newVreg(rc, sz);
            }
            Reg a = gen(e.E1);
            Reg d = newVreg(rc, sz);
            emitIns(op == OPabs ? LOp.fabs : LOp.fsqrt, sz, d, a);
            return d;
        }

        case OPcom:
        {
            Reg a = gen(e.E1);
            Reg d = newVreg(rc, sz);
            emitIns(LOp.mvn, sz <= 4 ? 4 : 8, d, a);
            return d;
        }

        case OPnot:
        case OPbool:
        {
            elem* e1 = e.E1;
            Reg a = gen(e1);
            if (tyfloating(e1.Ety))
                emitIns(LOp.fcmpz, tysize(e1.Ety), noReg, a);
            else
            {
                const sz1 = tysize(e1.Ety);
                if (sz1 < 4)
                    a = extend(a, e1.Ety, 4);
                emitIns(LOp.cmpi, sz1 <= 4 ? 4 : 8, noReg, a, noReg, 0);
            }
            Reg d = newVreg(RC.gp, sz);
            auto i = emitIns(LOp.cset, 4, d);
            i.cond = op == OPnot ? COND.eq : COND.ne;
            return d;
        }

        case OPlt: case OPle: case OPgt: case OPge: case OPeqeq: case OPne:
        {
            const c = compare(e);
            Reg d = newVreg(RC.gp, sz);
            auto i = emitIns(LOp.cset, 4, d);
            i.cond = c;
            return d;
        }

        case OPandand:
        case OPoror:
        {
            Reg d = newVreg(RC.gp, sz);
            const lfalse = newLabel();
            const lend = newLabel();
            defineHere(d);
            genCond(e, false, lfalse);
            emitIns(LOp.movi, 4, d, noReg, noReg, 1).flags |= F.condDef;
            jumpTo(lend);
            placeLabel(lfalse);
            emitIns(LOp.movi, 4, d, noReg, noReg, 0).flags |= F.condDef;
            placeLabel(lend);
            return d;
        }

        case OPcond:
        {
            Reg d = newVreg(rc, sz);
            const lfalse = newLabel();
            const lend = newLabel();
            defineHere(d);
            genCond(e.E1, false, lfalse);
            auto m = enterCond();
            Reg a = gen(e.E2.E1);
            copyOut(d, a, rc == RC.fp ? sz : 8);
            leaveCond(m);
            jumpTo(lend);
            placeLabel(lfalse);
            m = enterCond();
            Reg b = gen(e.E2.E2);
            copyOut(d, b, rc == RC.fp ? sz : 8);
            leaveCond(m);
            placeLabel(lend);
            return d;
        }

        case OPs32_64:
        case OPs16_32:
        case OPs8_16:
        {
            Reg a = gen(e.E1);
            Reg d = newVreg(RC.gp, sz);
            emitIns(LOp.sext, sz <= 4 ? 4 : 8, d, a, noReg, tysize(e.E1.Ety) * 8);
            return d;
        }

        case OPu32_64:
        case OPu16_32:
        case OPu8_16:
        {
            Reg a = gen(e.E1);
            Reg d = newVreg(RC.gp, sz);
            emitIns(LOp.zext, sz <= 4 ? 4 : 8, d, a, noReg, tysize(e.E1.Ety) * 8);
            return d;
        }

        case OP64_32:
        case OP32_16:
        case OP16_8:
            // the bits above a value's size are not relied on
            return gen(e.E1);

        case OPd_f:
        case OPf_d:
        {
            Reg a = gen(e.E1);
            Reg d = newVreg(RC.fp, sz);
            emitIns(LOp.fcvt, sz, d, a, noReg, tysize(e.E1.Ety));
            return d;
        }

        case OPs32_d: case OPs64_d:
        case OPu32_d: case OPu64_d:
        {
            Reg a = gen(e.E1);
            Reg d = newVreg(RC.fp, sz);
            const isz = tysize(e.E1.Ety);
            emitIns(op == OPs32_d || op == OPs64_d ? LOp.scvtf : LOp.ucvtf, sz, d, a, noReg, isz);
            return d;
        }

        case OPd_s32: case OPd_s64: case OPd_s16:
        case OPd_u32: case OPd_u64: case OPd_u16:
        {
            Reg a = gen(e.E1);
            Reg d = newVreg(RC.gp, sz);
            const signed = op == OPd_s32 || op == OPd_s64 || op == OPd_s16;
            emitIns(signed ? LOp.fcvtzs : LOp.fcvtzu, sz <= 4 ? 4 : 8, d, a, noReg, tysize(e.E1.Ety));
            return d;
        }

        case OPhalt:
            emitIns(LOp.brk, 0);
            return newVreg(RC.gp, 4);

        default:
            failed = true;
            return newVreg(rc, sz);
    }
}

/* e1 = e2
 */
@trusted
private Reg genAssign(elem* e)
{
    elem* e1 = e.E1;
    const ty = tybasic(e1.Ety);
    if (e1.Eoper == OPvar)
    {
        if (Reg r = varReg(e1.Vsym))
        {
            Reg v = gen(e.E2);
            copyOut(r, v, rcOf(r) == RC.fp ? tysize(ty) : 8);
            hintCopy(r, v);
            return r;
        }
        Reg v = gen(e.E2);
        store(v, memOf(e1), ty);
        return v;
    }
    if (e1.Eoper != OPind)
    {
        failed = true;
        return newVreg(RC.gp, 8);
    }
    Reg v;
    Mem m;
    if (ERTOL(e))
    {
        v = gen(e.E2);
        m = memOf(e1);
    }
    else
    {
        m = memOf(e1);
        v = genKeep(e.E2, m.base);
    }
    store(v, m, ty);
    return v;
}

/* Register copies a and b want the same register
 */
@trusted
private void hintCopy(Reg a, Reg b)
{
    if (!isPhys(b) && !vi(b).hint)
        vi(b).hint = a;
    if (!isPhys(a) && !vi(a).hint)
        vi(a).hint = b;
}

/* The operation of a binary operator on values of type ty
 */
private LOp binop(OPER op, tym_t ty)
{
    const fp = tyfloating(ty) != 0;
    const uns = tyuns(ty) != 0;
    switch (op)
    {
        case OPadd: case OPaddass: case OPpostinc: return fp ? LOp.fadd : LOp.add;
        case OPmin: case OPminass: case OPpostdec: return fp ? LOp.fsub : LOp.sub;
        case OPmul: case OPmulass:  return fp ? LOp.fmul : LOp.mul;
        case OPdiv: case OPdivass:  return fp ? LOp.fdiv : (uns ? LOp.udiv : LOp.sdiv);
        case OPmod: case OPmodass:  return uns ? LOp.udiv : LOp.sdiv;
        case OPand: case OPandass:  return LOp.and_;
        case OPor:  case OPorass:   return LOp.orr;
        case OPxor: case OPxorass:  return LOp.eor;
        case OPshl: case OPshlass:  return LOp.lslv;
        case OPshr: case OPshrass:  return LOp.lsrv;
        case OPashr: case OPashrass: return LOp.asrv;
        default: assert(0);
    }
}

/* d = a op b, with b possibly a constant, for values of type ty
 */
@trusted
private Reg arith(OPER op, tym_t ty, Reg a, elem* e2, Reg b)
{
    const sz = tysize(ty);
    const fp = tyfloating(ty) != 0;
    const isz = sz <= 4 ? 4 : 8;
    LOp lop = binop(op, ty);
    Reg d = newVreg(fp ? RC.fp : RC.gp, sz);

    if (fp)
    {
        emitIns(lop, sz, d, a, b);
        return d;
    }

    // operations whose result depends on the bits above the size
    const isMod = op == OPmod || op == OPmodass;
    if (sz < 4 && (lop == LOp.sdiv || lop == LOp.udiv || lop == LOp.lsrv || lop == LOp.asrv))
    {
        a = extend(a, ty, 4);
        if (lop == LOp.sdiv || lop == LOp.udiv)
            b = extend(b, ty, 4);
    }

    if (isMod)
    {
        Reg q = newVreg(RC.gp, sz);
        emitIns(lop, isz, q, a, b);
        auto i = emitIns(LOp.msub, isz, d, q, b);
        i.c = a;
        return d;
    }
    emitIns(lop, isz, d, a, b);
    return d;
}

/* The immediate form of lop for the constant v, or LOp.nop
 */
private LOp immForm(LOp lop, long v, uint isz)
{
    switch (lop)
    {
        case LOp.add: return v >= 0 && v < 4096 ? LOp.addi : (v < 0 && v > -4096 ? LOp.subi : LOp.nop);
        case LOp.sub: return v >= 0 && v < 4096 ? LOp.subi : (v < 0 && v > -4096 ? LOp.addi : LOp.nop);
        case LOp.lslv: return v >= 0 && v < isz * 8 ? LOp.lsli : LOp.nop;
        case LOp.lsrv: return v >= 0 && v < isz * 8 ? LOp.lsri : LOp.nop;
        case LOp.asrv: return v >= 0 && v < isz * 8 ? LOp.asri : LOp.nop;
        case LOp.and_:
        case LOp.orr:
        case LOp.eor:
        {
            uint N, immr, imms;
            const ulong u = isz == 4 ? cast(uint)v : cast(ulong)v;
            if (!encodeNImmrImms(isz == 4 ? (u | (u << 32)) : u, N, immr, imms))
                return LOp.nop;
            if (isz == 4 && N)
                return LOp.nop;
            return lop == LOp.and_ ? LOp.andi : lop == LOp.orr ? LOp.orri : LOp.eori;
        }
        default:
            return LOp.nop;
    }
}

@trusted
private Reg genBinary(elem* e)
{
    const op = e.Eoper;
    const ty = tybasic(e.Ety);
    const sz = tysize(ty);
    elem* e2 = e.E2;

    if (!tyfloating(ty) && e2.Eoper == OPconst && !e2.Ecount)
    {
        const isz = sz <= 4 ? 4 : 8;
        long v = el_tolong(e2);
        LOp lop = binop(op, ty);
        bool narrowShr = sz < 4 && (lop == LOp.lsrv || lop == LOp.asrv);
        LOp iop = narrowShr ? LOp.nop : immForm(lop, v, isz);
        if (iop != LOp.nop)
        {
            Reg a = gen(e.E1);
            Reg d = newVreg(RC.gp, sz);
            if ((lop == LOp.add && iop == LOp.subi) || (lop == LOp.sub && iop == LOp.addi))
                v = -v;
            emitIns(iop, isz, d, a, noReg, v);
            return d;
        }
    }

    Reg a, b;
    if (ERTOL(e))
    {
        b = gen(e2);
        a = gen(e.E1);
    }
    else
    {
        a = gen(e.E1);
        b = genKeep(e2, a);
    }
    if (tyfloating(ty) && tyfloating(e2.Ety) && tysize(e2.Ety) != sz)
    {
        failed = true;
        return newVreg(RC.fp, sz);
    }
    return arith(op, ty, a, e2, b);
}

/* e1 op= e2, and e1++ and e1--
 */
@trusted
private Reg genOpAssign(elem* e)
{
    const op = e.Eoper;
    elem* e1 = e.E1;
    const ty = tybasic(e1.Ety);
    const sz = tysize(ty);
    const fp = tyfloating(ty) != 0;
    const post = op == OPpostinc || op == OPpostdec;

    if (e1.Eoper == OPvar)
    {
        if (Reg r = varReg(e1.Vsym))
        {
            Reg b = gen(e.E2);
            Reg old;
            if (post)
            {
                old = newVreg(fp ? RC.fp : RC.gp, sz);
                emitIns(LOp.copy, fp ? sz : 8, old, r);
            }
            Reg d = arith(op, ty, r, e.E2, b);
            copyOut(r, d, fp ? sz : 8);
            hintCopy(r, d);
            return post ? old : r;
        }
    }
    else if (e1.Eoper != OPind)
    {
        failed = true;
        return newVreg(RC.gp, 8);
    }

    // in memory: E2 is evaluated first, as code generation does
    Reg b = gen(e.E2);
    Mem m = memOf(e1);
    Reg old = newVreg(fp ? RC.fp : RC.gp, sz);
    load(old, m, ty);
    Reg d = arith(op, ty, old, e.E2, b);
    store(d, m, ty);
    return post ? old : d;
}

/******************************* Liveness ******************************/

/* Position of instruction i: uses at 2i, definitions at 2i + 1
 */
private uint usePos(size_t i) { return cast(uint)(2 * i); }
private uint defPos(size_t i) { return cast(uint)(2 * i + 1); }

@trusted
private void forUses(ref LIns i, scope void delegate(Reg) nothrow dg)
{
    if (i.a) dg(i.a);
    if (i.b) dg(i.b);
    if (i.c) dg(i.c);
}

@trusted
private void addRange(Reg r, uint from, uint to)
{
    if (isPhys(r) || from >= to)
        return;
    auto rs = &vi(r).ranges;
    // ranges are added from the end of the function backward
    if (rs.length)
    {
        Range* first = &(*rs)[0];
        if (to >= first.from)
        {
            if (from < first.from)
                first.from = from;
            if (to > first.to)
                first.to = to;
            return;
        }
    }
    rs.push(Range(from, to));
    // keep sorted by moving the new first range to the front
    for (size_t k = rs.length - 1; k > 0; --k)
    {
        Range t = (*rs)[k];
        (*rs)[k] = (*rs)[k - 1];
        (*rs)[k - 1] = t;
    }
}

/* Shorten the range of r that starts at its block's start to start at pos,
 * for a definition
 */
@trusted
private void setFrom(Reg r, uint pos)
{
    if (isPhys(r))
        return;
    auto rs = &vi(r).ranges;
    if (rs.length == 0)
        rs.push(Range(pos, pos + 1));   // a definition never used
    else if ((*rs)[0].from <= pos)
        (*rs)[0].from = pos;
    else
    {
        rs.push(Range(pos, pos + 1));
        for (size_t k = rs.length - 1; k > 0; --k)
        {
            Range t = (*rs)[k];
            (*rs)[k] = (*rs)[k - 1];
            (*rs)[k - 1] = t;
        }
    }
}

private __gshared
{
    Barray!Reg globalRegs;              // by globalId
    Barray!ulong liveIn, liveOut;       // bit sets of globalIds by block
    size_t setWords;
}

@trusted
private void computeLiveness()
{
    const nb = blocks.length;

    // registers used in more than one block are global
    globalRegs.setLength(0);
    foreach (bi; 0 .. nb)
    {
        foreach (ref i; ins[blockStart[bi] .. blockStart[bi + 1]])
        {
            void see(Reg r)
            {
                if (isPhys(r))
                    return;
                auto v = vi(r);
                if (v.firstBlock == uint.max)
                    v.firstBlock = cast(uint)bi;
                else if (v.firstBlock != bi && v.globalId == uint.max)
                {
                    v.globalId = cast(uint)globalRegs.length;
                    globalRegs.push(r);
                }
            }
            if (i.d) see(i.d);
            forUses(i, &see);
        }
    }
    // variables are live across the whole function as needed
    foreach (k, r; symReg[])
    {
        if (r && vi(r).globalId == uint.max)
        {
            vi(r).globalId = cast(uint)globalRegs.length;
            globalRegs.push(r);
        }
    }

    setWords = (globalRegs.length + 63) / 64;
    Barray!ulong gen, kill;
    gen.setLength(nb * setWords);
    kill.setLength(nb * setWords);
    liveIn.setLength(nb * setWords);
    liveOut.setLength(nb * setWords);
    gen[][] = 0;
    kill[][] = 0;
    liveIn[][] = 0;
    liveOut[][] = 0;

    ulong[] row(ref Barray!ulong a, size_t bi) { return a[bi * setWords .. (bi + 1) * setWords]; }

    foreach (bi; 0 .. nb)
    {
        auto g = row(gen, bi);
        auto k = row(kill, bi);
        foreach (ref i; ins[blockStart[bi] .. blockStart[bi + 1]])
        {
            void use(Reg r)
            {
                if (isPhys(r)) return;
                const id = vi(r).globalId;
                if (id != uint.max && !(k[id / 64] & (1UL << (id % 64))))
                    g[id / 64] |= 1UL << (id % 64);
            }
            forUses(i, &use);
            if (i.d && !isPhys(i.d) && !(i.flags & F.condDef))
            {
                const id = vi(i.d).globalId;
                if (id != uint.max)
                    k[id / 64] |= 1UL << (id % 64);
            }
        }
    }

    // backward data flow to a fixed point
    bool changed = true;
    while (changed)
    {
        changed = false;
        foreach_reverse (bi; 0 .. nb)
        {
            auto o = row(liveOut, bi);
            foreach (s; blocks[bi].Bsucc[])
            {
                auto si = row(liveIn, s.Bdfoidx);
                foreach (w; 0 .. setWords)
                    o[w] |= si[w];
            }
            auto inn = row(liveIn, bi);
            auto g = row(gen, bi);
            auto k = row(kill, bi);
            foreach (w; 0 .. setWords)
            {
                const n = g[w] | (o[w] & ~k[w]);
                if (n != inn[w])
                {
                    inn[w] = n;
                    changed = true;
                }
            }
        }
    }
    gen.dtor();
    kill.dtor();

    // build the ranges backward
    foreach_reverse (bi; 0 .. nb)
    {
        const bfrom = usePos(blockStart[bi]);
        const bto = usePos(blockStart[bi + 1]);
        auto o = row(liveOut, bi);
        foreach (w; 0 .. setWords)
        {
            ulong bits = o[w];
            while (bits)
            {
                import core.bitop : bsf;
                const id = w * 64 + bsf(bits);
                bits &= bits - 1;
                addRange(globalRegs[id], bfrom, bto);
            }
        }
        const weight = blocks[bi].Bweight ? cast(float)blocks[bi].Bweight : 1;
        foreach_reverse (n; blockStart[bi] .. blockStart[bi + 1])
        {
            LIns* i = &ins[n];
            if (i.d && !isPhys(i.d))
            {
                if (i.flags & F.condDef)
                    addRange(i.d, defPos(n), defPos(n) + 1);    // may not be the value live before
                else
                    setFrom(i.d, defPos(n));
                vi(i.d).cost += weight;
            }
            void use(Reg r)
            {
                if (isPhys(r)) return;
                addRange(r, bfrom, usePos(n) + 1);
                vi(r).cost += weight;
            }
            forUses(*i, &use);
        }
    }
}

/******************************* Allocation ******************************/

/* The registers allocated, in order of preference: the caller saved first,
 * as they need no saving, then the callee saved
 */
private immutable ubyte[] gpOrder = [9,10,11,12,13,0,1,2,3,4,5,6,7, 19,20,21,22,23,24,25,26,27,28];
private immutable ubyte[] fpOrder = [32+16,32+17,32+18,32+19,32+20,32+21,32+22,32+23,32+24,32+25,32+26,32+27,32+28,
                                     32+0,32+1,32+2,32+3,32+4,32+5,32+6,32+7,
                                     32+8,32+9,32+10,32+11,32+12,32+13,32+14,32+15];

/* Registers reserved for loading and storing spilled values
 */
private immutable ubyte[3] gpScratch = [14, 15, 17];
private immutable ubyte[3] fpScratch = [32+29, 32+30, 32+31];

private __gshared Barray!Range[64] occupied;   // sorted ranges allocated to each register

@trusted
private bool overlaps(ref Barray!Range occ, ref Barray!Range rs)
{
    // both are sorted: merge walk
    size_t i, j;
    while (i < occ.length && j < rs.length)
    {
        if (occ[i].to <= rs[j].from)
            ++i;
        else if (rs[j].to <= occ[i].from)
            ++j;
        else
            return true;
    }
    return false;
}

@trusted
private void occupy(ref Barray!Range occ, ref Barray!Range rs)
{
    foreach (r; rs[])
    {
        // insert in order
        size_t k = occ.length;
        occ.push(r);
        while (k > 0 && occ[k - 1].from > r.from)
        {
            occ[k] = occ[k - 1];
            --k;
        }
        occ[k] = r;
    }
}

@trusted
private void allocate()
{
    foreach (ref o; occupied)
        o.setLength(0);

    // the physical registers are occupied from their definition to their last use
    // in the block, as parameters and return values are copied
    foreach (bi; 0 .. blocks.length)
    {
        uint[64] lastDef = uint.max;
        foreach (n; blockStart[bi] .. blockStart[bi + 1])
        {
            LIns* i = &ins[n];
            void use(Reg r)
            {
                if (!isPhys(r)) return;
                const p = physOf(r);
                const from = lastDef[p] == uint.max ? usePos(blockStart[bi]) : lastDef[p];
                occupied[p].push(Range(from, usePos(n) + 1));
            }
            forUses(*i, &use);
            if (isPhys(i.d))
            {
                // live until the end of the block, as for a return value
                occupied[physOf(i.d)].push(Range(defPos(n), usePos(blockStart[bi + 1]) + 1));
            }
        }
    }
    foreach (ref o; occupied)
    {
        // sort the few fixed ranges
        foreach (a; 1 .. o.length)
            for (size_t k = a; k > 0 && o[k - 1].from > o[k].from; --k)
            {
                Range t = o[k]; o[k] = o[k - 1]; o[k - 1] = t;
            }
    }

    // allocate the most costly first
    Barray!Reg order;
    foreach (k; 0 .. vinfo.length)
        if (vinfo[k].ranges.length)
            order.push(cast(Reg)(firstVreg + k));
    import core.stdc.stdlib : qsort;
    extern (C) static int cmp(scope const void* p, scope const void* q) nothrow
    {
        const a = *cast(const Reg*)p;
        const b = *cast(const Reg*)q;
        const ca = vinfo[a - firstVreg].cost;
        const cb = vinfo[b - firstVreg].cost;
        return ca > cb ? -1 : ca < cb ? 1 : (a < b ? -1 : a > b);
    }
    if (order.length > 1)
        qsort(order[].ptr, order.length, Reg.sizeof, &cmp);

    foreach (r; order[])
    {
        auto v = vi(r);
        const(ubyte)[] prefs = v.rc == RC.fp ? fpOrder : gpOrder;
        uint chosen = uint.max;
        // the register of the copy it comes from or goes to
        if (Reg h = v.hint)
        {
            uint p = uint.max;
            if (isPhys(h))
                p = physOf(h);
            else if (!vi(h).spilled && vi(h).preg != uint.max)
                p = vi(h).preg;
            if (p != uint.max && (p >= 32) == (v.rc == RC.fp) && allocatable(p, v.rc) &&
                !overlaps(occupied[p], v.ranges))
                chosen = p;
        }
        if (chosen == uint.max)
        {
            foreach (p; prefs)
                if (!overlaps(occupied[p], v.ranges))
                {
                    chosen = p;
                    break;
                }
        }
        if (chosen == uint.max)
        {
            v.spilled = true;
            continue;
        }
        v.preg = chosen;
        occupy(occupied[chosen], v.ranges);
    }
    order.dtor();
}

private bool allocatable(uint p, RC rc)
{
    foreach (q; rc == RC.fp ? fpOrder : gpOrder)
        if (q == p)
            return true;
    return false;
}

/* Replace the spilled registers by scratch registers loaded from and stored
 * to their stack slots
 */
@trusted
private void rewriteSpills()
{
    bool any;
    foreach (ref v; vinfo[])
        if (v.spilled)
            any = true;
    if (!any)
        return;

    Barray!LIns old;
    old.setLength(ins.length);
    old[][] = ins[][];
    Barray!uint oldStart;
    oldStart.setLength(blockStart.length);
    oldStart[][] = blockStart[][];
    ins.setLength(0);

    foreach (bi; 0 .. blocks.length)
    {
        blockStart[bi] = cast(uint)ins.length;
        foreach (n; oldStart[bi] .. oldStart[bi + 1])
        {
            LIns i = old[n];
            if (i.op == LOp.nop)
                continue;
            uint gpUsed, fpUsed;
            Reg scratch(RC rc)
            {
                return phys(rc == RC.fp ? fpScratch[fpUsed++] : gpScratch[gpUsed++]);
            }
            Symbol* slotOf(VInfo* v)
            {
                if (!v.slot)
                {
                    tym_t ty = v.rc == RC.fp ? (v.sz == 4 ? TYfloat : TYdouble) : TYllong;
                    v.slot = symbol_genauto(ty);
                    v.slot.Sfl = FL.auto_;
                }
                return v.slot;
            }
            void reload(ref Reg r)
            {
                if (!r || isPhys(r) || !vi(r).spilled)
                    return;
                auto v = vi(r);
                Reg s = scratch(v.rc);
                LIns l;
                l.op = LOp.ld;
                l.sz = v.rc == RC.fp ? v.sz : 8;
                l.d = s;
                l.sym = slotOf(v);
                ins.push(l);
                r = s;
            }
            // a register both used and defined is reloaded into the same scratch
            Reg defOrig = i.d;
            reload(i.a);
            reload(i.b);
            reload(i.c);
            Reg sd;
            if (i.d && !isPhys(i.d) && vi(i.d).spilled)
            {
                auto v = vi(i.d);
                sd = phys(v.rc == RC.fp ? fpScratch[0] : gpScratch[0]);
                i.d = sd;
            }
            ins.push(i);
            if (sd)
            {
                auto v = vi(defOrig);
                LIns s;
                s.op = LOp.st;
                s.sz = v.rc == RC.fp ? v.sz : 8;
                s.a = sd;
                s.sym = slotOf(v);
                ins.push(s);
            }
        }
    }
    blockStart[blocks.length] = cast(uint)ins.length;
    old.dtor();
    oldStart.dtor();
    usesFrame = true;
}

/******************************* Emission ******************************/

@trusted
private reg_t pr(Reg r)
{
    if (isPhys(r))
        return cast(reg_t)physOf(r);
    auto v = vi(r);
    assert(!v.spilled && v.preg != uint.max);
    return cast(reg_t)v.preg;
}

/* A load or store of a stack variable, built as getlvalue() does so
 * assignaddrc() fills in the offset
 */
@trusted
private void symEA(ref code cs, Symbol* s, long offset)
{
    cs.Iflags = CF.off;
    cs.IFL1 = s.Sfl;
    cs.IEV1.Vsym = s;
    cs.IEV1.Voffset = offset;
    cs.reg = NOREG;
    cs.index = NOREG;
    cs.base = 29;
    cs.Sextend = 0;
    s.Sflags |= SFLread;            // its memory is used
    if (s.Sfl == FL.para)
        cgp.refparam = true;
    else
        cgp.reflocal = true;
}

@trusted
private void emit(ref CGstate cg)
{
    // the code of each label
    Barray!(code*) labelCode;
    labelCode.setLength(nlabels);
    foreach (ref c; labelCode[])
    {
        c = code_calloc();
        c.Iop = INSTR.brk(0);       // not yet placed
    }

    regm_t used;
    foreach (bi, b; blocks[])
    {
        CodeBuilder cdb;
        cdb.ctor();
        foreach (n; blockStart[bi] .. blockStart[bi + 1])
        {
            LIns* i = &ins[n];
            emitOne(cdb, *i, labelCode, used);
        }
        b.Bcode = cdb.finish();
    }
    // the branches to labels refer to the label nops, now in place
    foreach (bi, b; blocks[])
    {
        for (code* c = b.Bcode; c; c = code_next(c))
        {
            if (c.IFL1 == FL.code && c.Iop != INSTR.nop)
            {
                const l = cast(uint)cast(size_t)c.IEV1.Vcode;
                c.IEV1.Vcode = labelCode[l];
                labelCode[l].Iflags |= CF.targ;
            }
        }
    }
    foreach (c; labelCode[])
        if (c.Iop != INSTR.nop)
            code_free(c);   // never placed
    labelCode.dtor();

    // the callee saved registers used are saved by the prolog
    cg.mfuncreg &= ~used;
}

@trusted
private void emitOne(ref CodeBuilder cdb, ref LIns i, ref Barray!(code*) labelCode, ref regm_t used)
{
    void def(uint p) { used |= mask(p); }
    const uint sf = i.sz == 8;

    switch (i.op)
    {
        case LOp.nop:
            break;

        case LOp.label:
        {
            // the label's code is a nop, which is not emitted
            code* c = labelCode[i.target];
            c.Iop = INSTR.nop;
            cdb.append(c);
            break;
        }

        case LOp.copy:
        {
            const d = pr(i.d), a = pr(i.a);
            def(d);
            if (d == a)
                break;
            if (d >= 32 && a >= 32)
                cdb.gen1(INSTR.fmov(INSTR.szToFtype(i.sz == 4 ? 4 : 8), a, d));
            else if (d < 32 && a < 32)
                cdb.gen1(INSTR.mov_register(1, a, d));
            else if (d >= 32)
                cdb.gen1(INSTR.fmov_float_gen(i.sz == 8, i.sz == 8 ? 1 : 0, 0, 7, a, d));
            else
                cdb.gen1(INSTR.fmov_float_gen(i.sz == 8, i.sz == 8 ? 1 : 0, 0, 6, a, d));
            break;
        }

        case LOp.movi:
        {
            const d = pr(i.d);
            def(d);
            movregconstant(cdb, cast(reg_t)d, sf ? cast(ulong)i.imm : cast(uint)i.imm, sf);
            break;
        }

        case LOp.fmovi:
        {
            const d = pr(i.d);
            def(d);
            double v;
            if (i.sz == 4)
            {
                uint bits = cast(uint)i.imm;
                v = *cast(float*)&bits;
            }
            else
            {
                long bits = i.imm;
                v = *cast(double*)&bits;
            }
            import dmd.backend.arm.disasmarm : encodeHFD;
            ubyte imm8;
            const ft = INSTR.szToFtype(i.sz);
            if (encodeHFD(v, imm8))
                cdb.gen1(INSTR.fmov_float_imm(ft, imm8, d));
            else
            {
                // the bits are put together in x16, which holds nothing allocated
                movregconstant(cdb, 16, i.sz == 8 ? cast(ulong)i.imm : cast(uint)i.imm, i.sz == 8);
                cdb.gen1(INSTR.fmov_float_gen(i.sz == 8, ft, 0, 7, 16, d));
            }
            break;
        }

        case LOp.add: case LOp.sub:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.addsub_shift(sf, i.op == LOp.sub, 0, 0, pr(i.b), 0, pr(i.a), d));
            break;
        }

        case LOp.mul:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.madd(sf, pr(i.b), 31, pr(i.a), d));
            break;
        }

        case LOp.msub:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.msub(sf, pr(i.b), pr(i.c), pr(i.a), d));
            break;
        }

        case LOp.sdiv: case LOp.udiv:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.sdiv_udiv(sf, i.op == LOp.udiv, pr(i.b), pr(i.a), d));
            break;
        }

        case LOp.and_: case LOp.orr: case LOp.eor:
        {
            const d = pr(i.d);
            def(d);
            const opc = i.op == LOp.and_ ? 0 : i.op == LOp.orr ? 1 : 2;
            cdb.gen1(INSTR.log_shift(sf, opc, 0, 0, pr(i.b), 0, pr(i.a), d));
            break;
        }

        case LOp.lslv: case LOp.lsrv: case LOp.asrv:
        {
            const d = pr(i.d);
            def(d);
            const opcode = i.op == LOp.lslv ? 8 : i.op == LOp.lsrv ? 9 : 10;
            cdb.gen1(INSTR.dp_2src(sf, 0, pr(i.b), opcode, pr(i.a), d));
            break;
        }

        case LOp.addi: case LOp.subi:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.addsub_imm(sf, i.op == LOp.subi, 0, 0, cast(uint)i.imm, pr(i.a), d));
            break;
        }

        case LOp.lsli:
        {
            const d = pr(i.d);
            def(d);
            const bits = sf ? 64 : 32;
            const sh = cast(uint)i.imm;
            cdb.gen1(INSTR.ubfm(sf, sf, (bits - sh) % bits, bits - 1 - sh, pr(i.a), d));
            break;
        }

        case LOp.lsri:
        {
            const d = pr(i.d);
            def(d);
            const bits = sf ? 64 : 32;
            cdb.gen1(INSTR.ubfm(sf, sf, cast(uint)i.imm, bits - 1, pr(i.a), d));
            break;
        }

        case LOp.asri:
        {
            const d = pr(i.d);
            def(d);
            const bits = sf ? 64 : 32;
            cdb.gen1(INSTR.sbfm(sf, sf, cast(uint)i.imm, bits - 1, pr(i.a), d));
            break;
        }

        case LOp.andi: case LOp.orri: case LOp.eori:
        {
            const d = pr(i.d);
            def(d);
            uint N, immr, imms;
            const ulong u = sf ? cast(ulong)i.imm : cast(uint)i.imm;
            encodeNImmrImms(sf ? u : (u | (u << 32)), N, immr, imms);
            const opc = i.op == LOp.andi ? 0 : i.op == LOp.orri ? 1 : 2;
            cdb.gen1(INSTR.log_imm(sf, opc, N, immr, imms, pr(i.a), d));
            break;
        }

        case LOp.neg:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.neg_sub_addsub_shift(sf, 0, 0, pr(i.a), 0, d));
            break;
        }

        case LOp.mvn:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.log_shift(sf, 1, 0, 1, pr(i.a), 0, 31, d));    // ORN d,zr,a
            break;
        }

        case LOp.sext: case LOp.zext:
        {
            const d = pr(i.d);
            def(d);
            const from = cast(uint)i.imm;           // bits
            if (i.op == LOp.zext && from == 32)
                cdb.gen1(INSTR.mov_register(0, pr(i.a), d));
            else if (i.op == LOp.zext)
                cdb.gen1(INSTR.ubfm(0, 0, 0, from - 1, pr(i.a), d));
            else
                cdb.gen1(INSTR.sbfm(sf, sf, 0, from - 1, pr(i.a), d));
            break;
        }

        case LOp.cmp:
            cdb.gen1(INSTR.cmp_subs_addsub_shift(sf, pr(i.b), 0, 0, pr(i.a)));
            break;

        case LOp.cmpi:
            cdb.gen1(INSTR.cmp_imm(sf, 0, cast(uint)i.imm, pr(i.a)));
            break;

        case LOp.cset:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.cset(0, i.cond ^ 1, d));        // CSINC with the inverse condition
            break;
        }

        case LOp.csel:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.csel(sf, pr(i.b), i.cond, pr(i.a), d));
            break;
        }

        case LOp.fadd: case LOp.fsub: case LOp.fmul: case LOp.fdiv:
        {
            const d = pr(i.d);
            def(d);
            const ft = INSTR.szToFtype(i.sz);
            const a = pr(i.a), b = pr(i.b);
            uint w;
            switch (i.op)
            {
                case LOp.fadd: w = INSTR.fadd_float(ft, b, a, d); break;
                case LOp.fsub: w = INSTR.fsub_float(ft, b, a, d); break;
                case LOp.fmul: w = INSTR.fmul_float(ft, b, a, d); break;
                default:       w = INSTR.fdiv_float(ft, b, a, d); break;
            }
            cdb.gen1(w);
            break;
        }

        case LOp.fneg: case LOp.fabs: case LOp.fsqrt:
        {
            const d = pr(i.d);
            def(d);
            const ft = INSTR.szToFtype(i.sz);
            const a = pr(i.a);
            cdb.gen1(i.op == LOp.fneg ? INSTR.fneg_float(ft, a, d) :
                     i.op == LOp.fabs ? INSTR.fabs_float(ft, a, d) :
                                        INSTR.fsqrt_float(ft, a, d));
            break;
        }

        case LOp.fcmp:
            cdb.gen1(INSTR.fcmp_float(INSTR.szToFtype(i.sz), pr(i.b), pr(i.a)));
            break;

        case LOp.fcmpz:
            cdb.gen1(INSTR.fcmp_float(INSTR.szToFtype(i.sz), 0, pr(i.a)) | 8);  // FCMP Vn,#0.0
            break;

        case LOp.fcsel:
        {
            const d = pr(i.d);
            def(d);
            cdb.gen1(INSTR.fcsel_float(INSTR.szToFtype(i.sz), pr(i.b), i.cond, pr(i.a), d));
            break;
        }

        case LOp.scvtf: case LOp.ucvtf:
        {
            const d = pr(i.d);
            def(d);
            const isf = i.imm == 8;
            const ft = INSTR.szToFtype(i.sz);
            cdb.gen1(i.op == LOp.scvtf ? INSTR.scvtf_float_int(isf, ft, pr(i.a), d)
                                       : INSTR.ucvtf_float_int(isf, ft, pr(i.a), d));
            break;
        }

        case LOp.fcvtzs: case LOp.fcvtzu:
        {
            const d = pr(i.d);
            def(d);
            const ft = INSTR.szToFtype(cast(uint)i.imm);
            cdb.gen1(i.op == LOp.fcvtzs ? INSTR.fcvtzs(sf, ft, pr(i.a), d)
                                        : INSTR.fcvtzu(sf, ft, pr(i.a), d));
            break;
        }

        case LOp.fcvt:
        {
            const d = pr(i.d);
            def(d);
            const ft = INSTR.szToFtype(cast(uint)i.imm);
            cdb.gen1(INSTR.fcvt_float(ft, i.sz == 4 ? 4 : 5, pr(i.a), d));
            break;
        }

        case LOp.ld:
        {
            const d = pr(i.d);
            def(d);
            code cs;
            if (i.sym)
                symEA(cs, i.sym, i.imm);
            else
            {
                cs.Iflags = CF.off;
                cs.IFL1 = FL.offset;
                cs.IEV1.Voffset = i.imm;
                cs.reg = NOREG;
                cs.index = NOREG;
                cs.base = cast(reg_t)pr(i.a);
                cs.Sextend = 0;
            }
            if (d < 32 && i.flags & F.signed)
                cs.Sextend = cast(ubyte)(i.sz == 1 ? Extend.SXTB : i.sz == 2 ? Extend.SXTH :
                                         i.sz == 4 ? Extend.SXTW : Extend.LSL);
            else if (d < 32)
                cs.Sextend = cast(ubyte)(i.sz == 1 ? Extend.UXTB : i.sz == 2 ? Extend.UXTH :
                                         i.sz == 4 ? Extend.UXTW : Extend.LSL);
            loadFromEA(cs, cast(reg_t)d, i.sz == 8 ? 8 : 4, i.sz);
            cdb.gen(&cs);
            break;
        }

        case LOp.st:
        {
            code cs;
            if (i.sym)
                symEA(cs, i.sym, i.imm);
            else
            {
                cs.Iflags = CF.off;
                cs.IFL1 = FL.offset;
                cs.IEV1.Voffset = i.imm;
                cs.reg = NOREG;
                cs.index = NOREG;
                cs.base = cast(reg_t)pr(i.b);
                cs.Sextend = 0;
            }
            storeToEA(cs, cast(reg_t)pr(i.a), i.sz);
            cdb.gen(&cs);
            break;
        }

        case LOp.lea:
        {
            const d = pr(i.d);
            def(d);
            Symbol* s = i.sym;
            code cs;
            symEA(cs, s, 0);
            cs.Iop = INSTR.addsub_imm(1, 0, 0, 0, 0, 29, d);
            cdb.gen(&cs);
            if (i.imm)
            {
                import dmd.backend.arm.cod3 : genaddimm;
                genaddimm(cdb, cast(reg_t)d, cast(reg_t)d, i.imm);
            }
            break;
        }

        case LOp.br:
        case LOp.bcond:
        {
            const cond = i.op == LOp.br ? COND.al : cast(COND)i.cond;
            if (i.flags & F.toLabel)
            {
                code cs;
                cs.Iop = INSTR.b_cond(0, cond);
                cs.Iflags = CF.zero;
                cs.IFL1 = FL.code;
                cs.IEV1.Vcode = cast(code*)cast(size_t)i.target;     // label number, resolved in emit()
                cdb.gen(&cs);
            }
            else
                genBranch(cdb, cond, FL.block, blocks[i.target]);
            break;
        }

        case LOp.brk:
            cdb.gen1(INSTR.brk(0));
            break;

        default:
            assert(0);
    }
}

/******************************* Debugging ******************************/

@trusted
private void dumpReg(Reg r)
{
    if (!r)
        return;
    if (isPhys(r))
    {
        const p = physOf(r);
        if (p >= 32)
            printf(" v%d", p - 32);
        else
            printf(" x%d", p);
    }
    else
        printf(" %%%d", r - firstVreg);
}

@trusted
private void dump()
{
    import dmd.backend.debugprint : WReqn;
    printf("=== %s\n", funcsym_p.Sident.ptr);
    foreach (bi; 0 .. blocks.length)
    {
        printf("B%d:\n", cast(int)bi);
        if (blocks[bi].Belem)
        {
            printf("  ");
            WReqn(blocks[bi].Belem);
            printf("\n");
        }
        foreach (n; blockStart[bi] .. blockStart[bi + 1])
        {
            auto i = &ins[n];
            printf("  %4d %-7s sz%d", cast(int)n, lopName(i.op), i.sz);
            dumpReg(i.d);
            printf(" <-");
            dumpReg(i.a);
            dumpReg(i.b);
            dumpReg(i.c);
            if (i.imm) printf(" #%lld", i.imm);
            if (i.sym) printf(" %s", i.sym.Sident.ptr);
            if (i.op == LOp.br || i.op == LOp.bcond || i.op == LOp.label)
                printf(" %s%d cond%d", i.flags & F.toLabel || i.op == LOp.label ? "L".ptr : "B".ptr, i.target, i.cond);
            printf("\n");
        }
    }
    foreach (k, ref v; vinfo[])
    {
        printf("%%%d rc%d sz%d cost%g %s", cast(int)k, v.rc, v.sz, v.cost,
            v.spilled ? "spilled".ptr : "".ptr);
        if (!v.spilled && v.preg != uint.max) printf(" -> %d", v.preg);
        if (v.sym) printf(" (%s)", v.sym.Sident.ptr);
        foreach (r; v.ranges[]) printf(" [%d,%d)", r.from, r.to);
        printf("\n");
    }
}

@trusted private const(char)* lopName(LOp op)
{
    switch (op)
    {
        static foreach (m; __traits(allMembers, LOp))
        {
            case __traits(getMember, LOp, m): return m.ptr;
        }
        default: return "?";
    }
}
