/* A template instance first instantiated speculatively, before the compilation is
 * split across worker processes, is generated by a worker that needs it.
DISABLED: win
REQUIRED_ARGS: -j=3
EXTRA_SOURCES: imports/parallel_spec_a.d imports/parallel_spec_b.d
*/

import imports.parallel_spec_b;

void main()
{
    auto close = &File.closeHandles;
    assert(close !is null);
}
